- hosts: vm
  remote_user: vagrant
  sudo: true
  gather_facts: no
  vars:
    user: vagrant
    home_directory: "/home/{{ user }}"
    deploy_to: "{{ home_directory }}"

  pre_tasks:
    - apt:
        name: git-core
        state: present

  roles:
    -
      role: nicolai86.prepare-release

      repo: https://github.com/nicolai86/ansible-prepare-release.git
      branch: master

      directories:
        - "{{ shared_path }}/examples"

      symlinks:
        - { src: "{{ shared_path }}/examples", dest: "{{ build_path }}/examples" }

      templates:
        - { src: "templates/bargrooves.j2", dest: "{{ shared_path }}/examples/paths" }

    - verify