---
- file:
    path: "{{ build_path }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"

- file:
    path: "{{ build_path }}/examples"
    state: directory

- file:
    path: "{{ deploy_to }}/scm"
    state: directory

- file:
    path: "{{ shared_path }}"
    state: directory

- file:
    path: "{{ deploy_to }}/releases"
    state: directory

- file:
    path: "{{ build_path }}/examples/paths"
    state: file

- stat:
    path: "{{ shared_path }}/examples/custom"
  register: custom_template

- fail:
    msg: "custom template parameters did not work"
  when: custom_template|failed or custom_template.stat.mode != "0744"
